server:
  port: 8081
spring:
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/vue?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
# 文件上传的
servlet:
  multipart:
    # 单个文件大小
    max-file-size: 10MB
    # 设置总上传的文件大小
    max-request-size: 20MB
file:
  path: D:/upload/
  url: http://localhost:8081/image/

mybatis-plus:
  # type-aliases-package: com.bjs.gsxtpt.
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:bjs:vsm: debug

global-config:
  # 数据库相关配置
  db-config:
    #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
  id-type: auto
    #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
  field-strategy: not_empty
    #驼峰下划线转换
  column-underline: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
  logic-delete-value: 1
  logic-not-delete-value: 0
  db-type: mysql
    #刷新mapper 调试神器
  refresh: true



